version: '3.7'

services:
  sql-server-db:
    container_name: 'sql-server-db'
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "SuperSenha123!@#"
      ACCEPT_EULA: "Y"